### ISSUE TITLE
IndexError: index out of range

### ISSUE THREAD

**Issue by tshippy** [elolab/VarSCAT#1]
I am trying to run the Tandem Repeat Annotation module, but I get the following error.

Start Tandem Repeat Annotation Module
Traceback (most recent call last):
  File "/Users/teresashippy/Applications/VarSCAT/VarSCAT.py", line 288, in <module>
    main()
  File "/Users/teresashippy/Applications/VarSCAT/VarSCAT.py", line 227, in main
    results_T = repeat_module(variant_df,lrp_df,reference_f,rmin,rmax,mtime,mmper,alignment_a,based,M_score,MI_score,G_score,R_check,S_except)
  File "/Users/teresashippy/Applications/VarSCAT/resource/read_VCF.py", line 222, in repeat_module
    item_repeat = search_repeats(df,ref,min_size,max_size,min_time,min_per,alignAS,bas,Mscore,MIscore,OGscore,Rcheck,Sexcept)
  File "/Users/teresashippy/Applications/VarSCAT/resource/Repeat_context.py", line 110, in search_repeats
    Repeat_raw_L0 = sizing_window(left_align,right_edge,REF,ALT,Ref,min_size0,max_size0,min_time0,min_per0,alignAS0,based0,Mscore0,MIscore0,OGscore0,Rcheck0,S_except0) 
  File "/Users/teresashippy/Applications/VarSCAT/resource/Repeat_context.py", line 17, in sizing_window
    mini_wiondow = sliding_window_mini(i,start,end,Ref2,alignAS2,based2,min_time2,min_per2,Mscore2,MIscore2,OGscore2,Rcheck2,S_except2)
  File "/Users/teresashippy/Applications/VarSCAT/resource/Repeat_context.py", line 57, in sliding_window_mini
    Repeat_raw_L3 = count_minisatellite(j,V_pattern,window_size,b,based3,min_time3,Mscore3,MIscore3,OGscore3,Rcheck3,S_except3)
  File "/Users/teresashippy/Applications/VarSCAT/resource/repeatAlign.py", line 57, in count_minisatellite
    Align_inner = alignment_pattern(pattern_start,search_size,ref,potential_R,1,size_except)
  File "/Users/teresashippy/Applications/VarSCAT/resource/repeatAlign.py", line 22, in alignment_pattern
    score_R = diff_letters(PR, potential_R_N)
  File "/Users/teresashippy/Applications/VarSCAT/resource/repeatAlign.py", line 5, in diff_letters
    common = sum(a[i]==b[i] for i in range(len(a)))
  File "/Users/teresashippy/Applications/VarSCAT/resource/repeatAlign.py", line 5, in <genexpr>
    common = sum(a[i]==b[i] for i in range(len(a)))
  File "/Users/teresashippy/anaconda3/envs/VarSCAT/lib/python3.9/site-packages/Bio/Seq.py", line 430, in __getitem__
    return chr(self._data[index])
IndexError: index out of range

I added some print statements after line 428 of Seq.py

 if isinstance(index, int):
            print("Debugging Indexing:")
            print("Index:", index)
            print("Length of self._data:", len(self._data))
            print("self._data")

The output indicates that the error always occurs when self.-data is  'TT'.  The length of self._data is correctly identified as 2, but it tries to retrieve index position 2 which does not exist.  Other two base sequences (including AA) seem to be handled correctly before this point, so I can't figure out why TT is failing. 

Thank you!
Teresa

**Comment by AuroUTU** [comment]
Hi Teresa,
Thank you very much for using my tool. Currently, I left Elo lab and start a new position, but I will try my best to maintain this tool (Please forgive me if I don't reply very quickly)
From the error messages, it seems that the tool failed when comparing two strings (one is repeat pattern, and one is potential repeat unit on reference sequence).
If possible, could you please share me the parameters you were using (including the reference sequence, I think VarSCAT can output all the parameters when running), and a demo file which contain this error-causing variant? 
Sometimes it is hard for me to know what happens without knowing the input. If it is not possible to share the demo file, my roughly guess is that maybe this variant is located in the end of the reference, so maybe the tool is searching 3bp repeat pattern, but on the reference it can only get 2bp because it is the end of the reference, then cause the error. Perhaps using the full reference may help. Sorry, this is just my guess.
My email address is wangningqd@outlook.com, if possible, you can send me the demo file (Or even share it here), and I will try my best to figure it out.

Have a nice day!

BEST
WANG Ning
